#!/bin/sh

str=$(mount | grep ' on / ')

if echo $str | grep -q 'ro'; then
  echo "------ INFO: / MOUNTED WITH \e[1mRO OVERLAY\e[0m ------\n"
elif echo $str | grep -q 'rw'; then
  echo "++++++ INFO: / MOUNTED \e[1mREAD-WRITE\e[0m ++++++\n"
else
  echo "!!!!!! [\e[31mWARNING\e[0m: / UNKNOWN STATE\e[0m !!!!!!\n"
fi
