#!/bin/bash
DIR="$1"
[ -z "${DIR}" ] && exit 1 

# change the overlay helper directories to be hidden, eg /home > /.home and /home/user > /home/.user
OFSDIR_PREFIX=${DIR%/*}/.${DIR##*/}
if [ ! -d "${OFSDIR_PREFIX}_org" ]; then
    echo "${OFSDIR_PREFIX}_org does not exist for root ${DIR}" >&2
    exit 1
fi
if [ ! -d "${OFSDIR_PREFIX}_rw" ]; then
    echo "${OFSDIR_PREFIX}_rw does not exist for root ${DIR}" >&2
    exit 1
fi
#
# ro must be the first mount option for root .....
#
ROOT_MOUNT=$( awk '$2=="/" { print substr($4,1,2) }' /proc/mounts )
if [ "$ROOT_MOUNT" != "ro" ]; then
    /bin/mount --bind ${OFSDIR_PREFIX}_org ${DIR}
else
    /bin/mount -t tmpfs ramdisk ${OFSDIR_PREFIX}_rw
    /bin/mkdir ${OFSDIR_PREFIX}_rw/upper
    /bin/mkdir ${OFSDIR_PREFIX}_rw/work
    OPTS="-o lowerdir=${OFSDIR_PREFIX}_org,upperdir=${OFSDIR_PREFIX}_rw/upper,workdir=${OFSDIR_PREFIX}_rw/work"
    /bin/mount -t overlay ${OPTS} overlay ${DIR}
fi
